### ISSUE TITLE
Labels with oblique or italic fonts look incorrect

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#3782]
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/GnWLZbIhKMk

![image](https://cloud.githubusercontent.com/assets/3451886/14080829/674547dc-f4d5-11e5-920e-28247212bb19.png)

```
var viewer = new Cesium.Viewer('cesiumContainer');

viewer.entities.add({
    position : Cesium.Cartesian3.fromDegrees(-75.1641667, 39.9522222),
    label : {
        text : 'Philadelphia',
        font : 'oblique 24pt Arial'
    }
});

viewer.entities.add({
    position : Cesium.Cartesian3.fromDegrees(-75.1641667, 32),
    label : {
        text : 'Philadelphia',
        font : 'italic 24pt Arial'
    }
});
```

**Comment by mramato** [comment]
I believe this is fixed by #2549, but I haven't tried it.

**Comment by mramato** [comment]
This is actually another manifestation of #2130 and will be fixed when that bug is addressed

**Comment by emackey** [comment]
@mramato actually, I think this is a separate bug.  I have some sample code I've been playing with that  pushes back the fringes of billboards into the Z buffer, which does fix 2130 but sadly is not compatible with translucent labels in their current implementation.  We should chat offline about that sometime.

That said, this issue appears different, as it is not fixed with the same technique.  My guess is that the slanted glyphs are actually sticking out past the right-hand edge of their allotment in the texture atlas, and getting cropped.  As such I would expect your font-kerning branch to fix this by rendering all the glyphs together.  But the low-alpha z-buffered translucency thing is not the problem here.

**Comment by mramato** [comment]
@emackey to clarify, I think the `font-kerning` branch and #2130 together are what will address this issue.

Also, while it's good you might have an alternative solution for the transparency issue, I will point out that a surprising number of browser/device combos do not support frag depth (IE11, iOS, many android devices), so anything requiring it is not an ideal solution for something as common as billboard transparency.

**Comment by emackey** [comment]
@mramato Yeah, I may have mis-remembered what font-kerning was actually doing, is each letter still a separate glyph?  If so this bug stands:  I think the individual slanted glyphs are getting cropped, not z-buffered out of existence here.

**Comment by emackey** [comment]
For example, there should be no Z buffer issue with a single lone letter:

```
var viewer = new Cesium.Viewer('cesiumContainer');

viewer.entities.add({
    position : Cesium.Cartesian3.fromDegrees(-75.1641667, 39.9522222),
    label : {
        text : 'd',
        font : 'oblique 24pt Arial'
    }
});

viewer.entities.add({
    position : Cesium.Cartesian3.fromDegrees(-75.1641667, 32),
    label : {
        text : 'd',
        font : 'italic 24pt Arial'
    }
});
```

**Comment by mramato** [comment]
Yes, each label is a separate glyph (which is absolutely required for performance/memory), but the code that generates the glyphs was fixed to properly take width into account.  That being said, it's totally possible that oblique letters still cause problems so additional changes to the font-keming branch might be needed (in addition to the transparency fix to support proper kerning).

**Comment by GatorScott** [comment]
The problem with italic (and bold) text is that measureText does not apply font-style and font-weight to the text being measured.  There also is a problem computing the width of the character.
![philadelphia](https://cloud.githubusercontent.com/assets/4126790/14217644/4e517cd2-f81d-11e5-946d-883bbe5d5154.png)

**Comment by GatorScott** [comment]
I've been unable to figure out how to get my changes into a pull request, so they are attached.

[Issue-3782.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/201376/Issue-3782.zip)

**Comment by pjcozzi** [comment]
Contacted @GatorScott offline about getting help opening a PR.
